pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'cd mi-proyecto && mvn clean install'
      }
    }

    stage('Test') {
      steps {
        sh 'cd mi-proyecto && mvn test'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Simulating deployment...'
      }
    }
  }

  post {
    always {
      echo 'Pipeline finished.'
    }
    success {
      echo 'Build and tests succeeded!'
    }
    failure {
      echo 'Build or tests failed.'
    }
  }
}